/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "GestorBiblioteca.h"
#include <stdlib.h>
#include <time.h>
#include <string.h>
#include <stdio.h>
#include <ctype.h>
#include <unistd.h>

#define Cls system("clear")
#define Pause system("read -p \"Pulsa la tecla return para continuar..... \" a")

#define MostrarAviso(Texto) \
	{                       \
		printf(Texto);      \
		Pause;              \
	}
extern TLibro *Biblioteca;
extern int NumLibros;

int MenuPrincipal()
{
	int Salida;
	do
	{
		Cls;
		printf(" GESTOR BIBLIOTECARIO 1.0 (M. PRINCIPAL)\n");
		printf("*****************************************\n");
		printf("\t1.- M. Administración\n");
		printf("\t2.- Consulta de libros\n");
		printf("\t3.- Préstamo de libros\n");
		printf("\t4.- Devolución de libros\n");
		printf("\t0.- Salir\n\n");
		printf(" Elige opción: ");
		scanf("%d", &Salida);
		if (Salida < 0 || Salida > 4)
			MostrarAviso("\n\n *** Error en la entrada de Datos.***\n\n");
	} while (Salida < 0 || Salida > 4);
	return Salida;
}

int MenuAdministracion()
{
	int Salida;
	do
	{
		Cls;
		printf(" GESTOR BIBLIOTECARIO 1.0 (M. ADMINISTRACION)\n");
		printf("**********************************************\n");
		printf("\t1.- Cargar datos Biblioteca\n");
		printf("\t2.- Guardar datos Biblioteca\n");
		printf("\t3.- Nuevo libro\n");
		printf("\t4.- Comprar libros\n");
		printf("\t5.- Retirar libros\n");
		printf("\t6.- Ordenar libros\n");
		printf("\t7.- Buscar libros\n");
		printf("\t8.- Listar libros\n");
		printf("\t0.- Salir\n\n");
		printf(" Elige opción: ");
		scanf("%d", &Salida);
		if (Salida < 0 || Salida > 8)
			MostrarAviso("\n\n *** Error en la entrada de Datos.***\n\n");
	} while (Salida < 0 || Salida > 8);
	return Salida;
}

void Formatea(char *Salida, const char *p, int ancho, char Caracter)
{
	Cadena vacia;
	int len = ancho - strlen(p);
	int l = 0, c = 0;

	while (p[l] != '\0')
	{
		if ((unsigned char)p[l] > 128)
			c++;
		l++;
	}
	len += c / 2;

	if (len < 0)
		len = 0;
	for (int i = 0; i < len; i++)
		vacia[i] = Caracter;
	vacia[len] = '\0';

	sprintf(Salida, "%s%s", p, vacia);
}

void MostrarLibro(TLibro *L, int Pos, bool_t Cabecera)
{
	Cadena T, A, B, PI;
	if (Cabecera == TRUE)
	{
		printf("%-*s%-*s%-*s%*s%*s%*s\n", 5, "POS", 58, "TITULO", 18, "ISBN", 4, "DIS", 4, "PRE", 4, "RES");
		printf("     %-*s%-*s%-*s\n", 30, "AUTOR", 28, "PAIS (IDIOMA)", 12, "AÑO");
		Formatea(B, "*", 93, '*');
		printf("%s\n", B);
	}
	Formatea(T, L->Titulo, 58, ' ');
	Formatea(A, L->Autor, 30, ' ');
	strcpy(B, L->Pais);
	strcat(B, " (");
	strcat(B, L->Idioma);
	strcat(B, ")");
	Formatea(PI, B, 28, ' ');
	printf("%-5d%s%-*s%*d%*d%*d\n", Pos + 1, T, 18, L->Isbn, 4, L->NoLibros, 4, L->NoPrestados, 4, L->NoListaEspera);
	printf("     %s%s%-*d\n", A, PI, 12, L->Anio);
}

int *func_conexion(CLIENT *clnt)
{
	int *result_1_puntero;
	Cadena contraseña = "1234";

	result_1_puntero = conexion_1(contraseña, clnt);
	if (result_1_puntero == (int *)NULL)
	{
		clnt_perror(clnt, "call failed");
		*result_1_puntero = 0;
	}
	else
	{
		printf("Numero que devuelve la funcion conexion %d\n", *result_1_puntero);
	}
	sleep(1);
	return result_1_puntero;
}

void func_desconexion(int *result_1_puntero, CLIENT *clnt)
{

	bool_t *result_2_puntero;
	int desconexion_arg = *result_1_puntero;

	result_2_puntero = desconexion_1(&desconexion_arg, clnt);
	if (result_2_puntero == (bool_t *)NULL)
	{
		clnt_perror(clnt, "call failed");
	}
	else
	{
		printf("Numero que devuelve la funcion desconexion %d\n", *result_2_puntero);
	}

	sleep(1);
}

void func_cargar_datos(int *result_1_puntero, CLIENT *clnt)
{

	int *result_3_puntero;
	TConsulta cargardatos_1_arg;
	cargardatos_1_arg.Ida = *result_1_puntero;
	strcpy(cargardatos_1_arg.Datos, "Biblioteca.cdat");

	result_3_puntero = cargardatos_1(&cargardatos_1_arg, clnt);
	if (result_3_puntero == (int *)NULL)
	{
		clnt_perror(clnt, "call failed");
		printf("error en primer cargar datos\n");
	}
	else
	{
		printf("Numero que devuelve la funcion cargardatos %d\n", *result_3_puntero);
	}

	sleep(1);
}

void func_guardar_datos(int *result_1_puntero, CLIENT *clnt)
{

	bool_t *result_4_puntero;
	int guardardatos_1_arg = *result_1_puntero;

	result_4_puntero = guardardatos_1(&guardardatos_1_arg, clnt);
	if (result_4_puntero == (bool_t *)NULL)
	{
		clnt_perror(clnt, "call failed");
	}
	else
	{
		printf("Numero que devuelve la funcion guardardatos %d\n", *result_4_puntero);
	}

	sleep(1);
}

void func_nuevo_libro(int *result_1_puntero, CLIENT *clnt)
{

	int *result_5_puntero;
	TNuevo nuevolibro_1_arg;
	nuevolibro_1_arg.Ida = *result_1_puntero;
	strcpy(nuevolibro_1_arg.Libro.Isbn, "1234");
	strcpy(nuevolibro_1_arg.Libro.Titulo, "Esto es un titulo de prueba");
	strcpy(nuevolibro_1_arg.Libro.Autor, "Jesus");
	nuevolibro_1_arg.Libro.Anio = 2024;
	strcpy(nuevolibro_1_arg.Libro.Pais, "Espana");
	strcpy(nuevolibro_1_arg.Libro.Idioma, "Espanol");
	nuevolibro_1_arg.Libro.NoLibros = 1;
	nuevolibro_1_arg.Libro.NoListaEspera = 2;
	nuevolibro_1_arg.Libro.NoPrestados = 0;

	result_5_puntero = nuevolibro_1(&nuevolibro_1_arg, clnt);
	if (result_5_puntero == (int *)NULL)
	{
		clnt_perror(clnt, "call failed");
		printf("error en nuevo libro\n");
	}
	else
	{
		printf("Numero que devuelve la funcion nuevolibro %d\n", *result_5_puntero);
	}

	sleep(1);
}

void func_comprar_libros(int *result_1_puntero, CLIENT *clnt)
{

	int *result_6_puntero;
	TComRet comprar_1_arg;
	comprar_1_arg.Ida = *result_1_puntero;
	strcpy(comprar_1_arg.Isbn, "1234");
	comprar_1_arg.NoLibros = 5;

	result_6_puntero = comprar_1(&comprar_1_arg, clnt);
	if (result_6_puntero == (int *)NULL)
	{
		clnt_perror(clnt, "call failed");
	}
	else
	{
		printf("Numero que devuelve la funcion comprar %d\n", *result_6_puntero);
	}
	sleep(1);
}

void func_retirar_libros(int *result_1_puntero, CLIENT *clnt)
{

	int *result_7_puntero;
	TComRet retirar_1_arg;
	retirar_1_arg.Ida = *result_1_puntero;
	strcpy(retirar_1_arg.Isbn, "1234");
	retirar_1_arg.NoLibros = 3;

	result_7_puntero = retirar_1(&retirar_1_arg, clnt);
	if (result_7_puntero == (int *)NULL)
	{
		clnt_perror(clnt, "call failed");
	}
	else
	{
		printf("Numero que devuelve la funcion retirar %d\n", *result_7_puntero);
	}
	sleep(1);
}

void func_ordenar(int *result_1_puntero, CLIENT *clnt)
{

	bool_t *result_8_puntero;
	TOrdenacion ordenar_1_arg;
	ordenar_1_arg.Ida = *result_1_puntero;
	ordenar_1_arg.Campo = 0;

	result_8_puntero = ordenar_1(&ordenar_1_arg, clnt);
	if (result_8_puntero == (bool_t *)NULL)
	{
		clnt_perror(clnt, "call failed");
	}
	else
	{
		printf("Numero que devuelve la funcion ordenar %d\n", *result_8_puntero);
	}
	sleep(1);
}

void func_nlibros(int *result_1_puntero, CLIENT *clnt)
{

	int *result_9_puntero;
	int nlibros_1_arg = *result_1_puntero;

	result_9_puntero = nlibros_1(&nlibros_1_arg, clnt);
	if (result_9_puntero == (int *)NULL)
	{
		clnt_perror(clnt, "call failed");
	}
	else
	{
		printf("Numero que devuelve la funcion nlibros %d\n", *result_9_puntero);
	}
	sleep(1);
}

void func_buscar(int *result_1_puntero, CLIENT *clnt)
{

	int *result_10_puntero;
	TConsulta buscar_1_arg;
	buscar_1_arg.Ida = *result_1_puntero;
	strcpy(buscar_1_arg.Datos, "0-019153-721161");

	result_10_puntero = buscar_1(&buscar_1_arg, clnt);
	if (result_10_puntero == (int *)NULL)
	{
		clnt_perror(clnt, "call failed");
	}
	else
	{
		printf("Numero que devuelve la funcion buscar %d\n", *result_10_puntero);
	}
	sleep(1);
}

void func_descargar(int *result_1_puntero, CLIENT *clnt)
{

	TLibro *result_11_puntero;
	TPosicion descargar_1_arg;
	descargar_1_arg.Ida = *result_1_puntero;
	descargar_1_arg.Pos = 0;

	result_11_puntero = descargar_1(&descargar_1_arg, clnt);
	if (result_11_puntero == (TLibro *)NULL)
	{
		clnt_perror(clnt, "call failed");
	}
	else
	{
		printf("Isbn: %s\n", result_11_puntero->Isbn);
		printf("Autor: %s\n", result_11_puntero->Autor);
		printf("Idioma: %s\n", result_11_puntero->Idioma);
		printf("Pais: %s\n", result_11_puntero->Pais);
		printf("Titulo: %s\n", result_11_puntero->Titulo);
		printf("Anio: %d\n", result_11_puntero->Anio);
		printf("Numero de libros: %d\n", result_11_puntero->NoLibros);
		printf("Numero de usuarios en espera: %d\n", result_11_puntero->NoListaEspera);
		printf("Numero de libros prestados: %d\n", result_11_puntero->NoPrestados);
	}
	sleep(1);
}

void func_prestar(int *result_1_puntero, CLIENT *clnt){

	int *result_12_puntero;
	
	TPosicion prestar_1_arg;

	prestar_1_arg.Ida = *result_1_puntero;
	prestar_1_arg.Pos = 0;

	result_12_puntero = prestar_1(&prestar_1_arg, clnt);
	if (result_12_puntero == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else{
		printf("Numero que devuelve la fucion prestar %d\n",*result_12_puntero);
	}
	sleep(1);
}

void gestorbiblioteca_1(char *host)
{
	CLIENT *clnt;
	int *ida;

	int *result_13;
	TPosicion devolver_1_arg;

#ifndef DEBUG
	clnt = clnt_create(host, GESTORBIBLIOTECA, GESTORBIBLIOTECA_VER, "tcp");
	if (clnt == NULL)
	{
		clnt_pcreateerror(host);
		exit(1);
	}
#endif /* DEBUG */

	printf("Conexion correcta con el servidor\n");

	//------------------------------CONEXION-------------------------------------------------------
	ida = func_conexion(clnt);

	//-------------------------------DESCONEXION---------------------------------------------------
	// func_desconexion(ida,clnt);

	//------------------------------CARGAR DATOS---------------------------------------------------
	func_cargar_datos(ida, clnt);

	//------------------------------GUARDAR DATOS--------------------------------------------------
	 //func_guardar_datos(ida,clnt);

	//------------------------------NUEVO LIBRO----------------------------------------------------
	//func_nuevo_libro(ida, clnt);

	//-------------------------------COMPRAR-------------------------------------------------------
	// func_comprar_libros(ida,clnt);
	//func_guardar_datos(ida, clnt);
	//func_cargar_datos(ida, clnt);

	//-------------------------------RETIRAR-------------------------------------------------------
	// func_retirar_libros(ida,clnt);
	// func_guardar_datos(ida,clnt);
	// func_cargar_datos(ida,clnt);

	//-------------------------------ORDENAR-------------------------------------------------------
	// func_ordenar(ida,clnt);
	// func_guardar_datos(ida,clnt);
	// func_cargar_datos(ida,clnt);

	//-------------------------------NLIBROS--------------------------------------------------------
	// func_nlibros(ida, clnt);

	//-------------------------------BUSCAR---------------------------------------------------------
	// func_buscar(ida,clnt);

	//-------------------------------DESCARGAR------------------------------------------------------
	func_descargar(ida, clnt);
	
	//--------------------------------PRESTAR-------------------------------------------------------
	func_prestar(ida,clnt);
	func_descargar(ida,clnt);

	/*
	
	result_13 = devolver_1(&devolver_1_arg, clnt);
	if (result_13 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}*/
#ifndef DEBUG
	clnt_destroy(clnt);
#endif /* DEBUG */
}

int main(int argc, char *argv[])
{
	char *host;

	if (argc < 2)
	{
		printf("usage: %s server_host\n", argv[0]);
		exit(1);
	}
	host = argv[1];
	gestorbiblioteca_1(host);
	exit(0);
}
